export const mockLaptops = [
  {
    id: "1",
    brand: "Dell",
    model: "XPS 15",
    processor: "Intel Core i7-11800H",
    ram: "16GB",
    storage: "512GB SSD",
    graphics: "NVIDIA RTX 3050",
    display: "15.6\" FHD",
    condition: "NEW",
    price: 8500,
    availability: true,
    hasBacklight: true,
    hasFingerprint: true,
    hasWebcam: true,
    hasUsbC: true,
    hasHdmi: true,
    hasSdCardReader: false,
    hasNumericPad: false,
    operatingSystem: "Windows 11",
    weight: 1.8,
    batteryLife: 8,
    warranty: 24,
    material: "Aluminum",
    description: "High-performance laptop for professionals",
    imageUrls: "https://via.placeholder.com/400x300",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01"
  },
  {
    id: "2",
    brand: "HP",
    model: "Pavilion 14",
    processor: "Intel Core i5-1135G7",
    ram: "8GB",
    storage: "256GB SSD",
    graphics: "Intel Iris Xe",
    display: "14\" FHD",
    condition: "UK_USED",
    price: 3500,
    availability: true,
    hasBacklight: true,
    hasFingerprint: false,
    hasWebcam: true,
    hasUsbC: true,
    hasHdmi: true,
    hasSdCardReader: true,
    hasNumericPad: false,
    operatingSystem: "Windows 10",
    weight: 1.4,
    batteryLife: 7,
    warranty: 6,
    material: "Plastic",
    description: "Great for students and everyday use",
    imageUrls: "https://via.placeholder.com/400x300",
    createdAt: "2024-01-01",
    updatedAt: "2024-01-01"
  }
];